# Generated by Django 5.0.6 on 2024-06-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_category_commune_customer_order_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='imagenes/'),
        ),
    ]
